service-base-chart:
  applicationName: kamino-lending-liquidations-bot
  image:
    repository: hubbleprotocol/kamino-lending-liquidations-bot
    tag: "latest"
  containerPorts:
    - name: http
      containerPort: 80
      protocol: TCP
  volumeMounts:
    - name: kamino-lending-liquidations-bot-secret-vol
      mountPath: /root/.kamino-lending
      readOnly: true
  volumes:
    - name: kamino-lending-liquidations-bot-secret-vol
      secret:
        secretName: kamino-lending-liquidations-bot-secret
        defaultMode: 292
  service:
    additionalLabels:
      prometheus-monitor: hubble-prom-metrics
  envVars:
    - name: SERVER_PORT
      value: "80"
    - name: NODE_ENV
      value: devnet
    - name: APP
      value: devnet
    - name: RPC_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: solana-rpc-cluster-secret
          key: DEVNET_ENDPOINT
    - name: SECRET_PATH
      value: /root/.kamino-lending/keypair.json
    - name: REBALANCE_PADDING
      value: "0.2"
    - name: TARGETS
      value: >- 
        'USDC:100 SOL:0.5 ETH:0.05 BTC:0.001 stSOL:0.1'
    - name: THROTTLE
      value: "10"
  secrets:
    keypair.json:

